## Get Rider coordinates

###GET http://localhost:3002/rider-coordinates

##POST Rider coordinates    
POST http://localhost:3002/rider-coordinates
Content-Type: application/json

{

    "lat": 37.7749,
    "lng": -122.4194
}
